create table if not exists gps_tracking (
  id bigint generated by default as identity primary key,
  nip text not null,
  user_id text,
  latitude numeric(10,7) not null,
  longitude numeric(10,7) not null,
  horizontal_accuracy numeric(6,1),
  recorded_at timestamptz not null default now(),
  tanggal_iso date generated always as (recorded_at::date) stored,
  device text,
  created_at timestamptz not null default now()
);

create index if not exists idx_gps_tracking_nip_tanggal on gps_tracking(nip, tanggal_iso);
create index if not exists idx_gps_tracking_recorded_at on gps_tracking(recorded_at);
