-- ═══════════════════════════════════════════════════════════════
-- MIGRATION 004: Auth Sessions + Biometric Storage
-- ═══════════════════════════════════════════════════════════════
-- 1. auth_sessions: Per-user session tokens (gantikan static API_TOKEN)
-- 2. Cleanup face descriptor duplication

-- ── TABEL SESSIONS ──
create table if not exists auth_sessions (
  id bigint generated by default as identity primary key,
  session_token text not null unique,
  nip text not null,
  user_id text,
  role text not null default 'USER',
  instansi_id text not null default '',
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  last_used_at timestamptz,
  is_active boolean not null default true
);

create index if not exists idx_sessions_token on auth_sessions(session_token);
create index if not exists idx_sessions_nip_active on auth_sessions(nip, is_active) where is_active = true;

-- ── FUNCTION: Bersihkan session expired ──
create or replace function clean_expired_sessions()
returns void
language plpgsql
as $$
begin
  update auth_sessions set is_active = false
  where is_active = true and expires_at < now();
end;
$$;

-- ── FUNCTION: Validasi session & return role ──
-- Dipanggil dari n8n untuk tiap request admin/protected
create or replace function validate_session(p_token text)
returns table(
  nip text,
  role text,
  instansi_id text,
  is_valid boolean
)
language plpgsql
stable
as $$
begin
  -- Clean expired first
  update auth_sessions set is_active = false
  where is_active = true and expires_at < now();

  return query
  select
    s.nip,
    s.role,
    s.instansi_id,
    (s.is_active and s.expires_at > now()) as is_valid
  from auth_sessions s
  where s.session_token = p_token
  limit 1;

  -- Touch last_used_at if valid
  update auth_sessions s
  set last_used_at = now()
  where s.session_token = p_token
    and s.is_active = true
    and s.expires_at > now();
end;
$$;

-- ── FUNCTION: Buat session baru ──
create or replace function create_session(
  p_nip text,
  p_user_id text,
  p_role text default 'USER',
  p_instansi_id text default ''
)
returns text  -- returns session_token
language plpgsql
as $$
declare
  v_token text;
  v_expires timestamptz;
begin
  v_token := encode(gen_random_bytes(48), 'hex');
  v_expires := now() + interval '24 hours';

  -- Deactivate old sessions for this user
  update auth_sessions set is_active = false
  where nip = p_nip and is_active = true;

  insert into auth_sessions (session_token, nip, user_id, role, instansi_id, expires_at)
  values (v_token, p_nip, p_user_id, p_role, p_instansi_id, v_expires);

  return v_token;
end;
$$;

-- ── FUNCTION: Perpanjang session ──
create or replace function extend_session(p_token text, p_hours int default 24)
returns boolean
language plpgsql
as $$
begin
  update auth_sessions
  set expires_at = now() + (p_hours || ' hours')::interval,
      last_used_at = now()
  where session_token = p_token
    and is_active = true
    and expires_at > now();
  return found;
end;
$$;
